# Generated by Django 5.1.7 on 2025-12-06 14:30

import core.utils
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
                ("symbol", models.CharField(max_length=10)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("unit", "Unit"),
                            ("weight", "Weight"),
                            ("volume", "Volume"),
                            ("length", "Length"),
                            ("time", "Time"),
                        ],
                        default="unit",
                        max_length=20,
                    ),
                ),
                (
                    "ratio",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        help_text="Conversion ratio to base unit",
                        max_digits=12,
                    ),
                ),
                (
                    "is_base_unit",
                    models.BooleanField(
                        default=False,
                        help_text="Is this the base unit for its category?",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit of Measure",
                "verbose_name_plural": "Units of Measure",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "internal_reference",
                    models.CharField(
                        blank=True,
                        help_text="Internal code/SKU",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                ("barcode", models.CharField(blank=True, max_length=50, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("consumable", "Consumable"),
                            ("stockable", "Stockable"),
                            ("service", "Service"),
                        ],
                        default="stockable",
                        max_length=20,
                    ),
                ),
                (
                    "cost_method",
                    models.CharField(
                        choices=[
                            ("standard", "Standard Price"),
                            ("average", "Average Cost"),
                            ("fifo", "First In First Out"),
                        ],
                        default="average",
                        max_length=20,
                    ),
                ),
                (
                    "standard_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost price",
                        max_digits=12,
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sales price",
                        max_digits=12,
                    ),
                ),
                ("can_be_purchased", models.BooleanField(default=True)),
                ("can_be_sold", models.BooleanField(default=True)),
                (
                    "reorder_point",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Minimum stock level before reorder",
                        max_digits=12,
                    ),
                ),
                (
                    "reorder_qty",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Default quantity to reorder",
                        max_digits=12,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.category",
                    ),
                ),
                (
                    "purchase_uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Unit used when purchasing (if different)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_products",
                        to="products.unitofmeasure",
                        verbose_name="Purchase Unit of Measure",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        help_text="Default unit for stock and sales",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="products.unitofmeasure",
                        verbose_name="Unit of Measure",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
