# Generated by Django 5.1.7 on 2025-12-07 13:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="bill_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Amount billed by vendor",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="bill_date",
            field=models.DateField(
                blank=True, help_text="Date of vendor bill", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="bill_reference",
            field=models.CharField(
                blank=True, help_text="Vendor bill/invoice reference", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_date",
            field=models.DateField(
                blank=True, help_text="Date payment was made", null=True
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="payment_reference",
            field=models.CharField(
                blank=True, help_text="Payment reference", max_length=100
            ),
        ),
    ]
