# Generated by Django 5.1.7 on 2025-12-06 19:10

from django.utils import timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payrolls", "0003_alter_payroll_month"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payroll",
            options={"ordering": ["-month", "actor"]},
        ),
        migrations.AlterField(
            model_name="payroll",
            name="month",
            field=models.DateField(default=timezone.now),
        ),
        migrations.AddConstraint(
            model_name="payroll",
            constraint=models.UniqueConstraint(
                fields=("actor", "month"), name="unique_payroll_per_employee_month"
            ),
        ),
    ]
