# Generated by Django 5.1.7 on 2025-12-06 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payrolls", "0005_payroll_employee_and_month"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payroll",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="payroll",
            name="unique_payroll_per_employee_month",
        ),
    ]
