# Generated by Django 5.1.7 on 2025-12-13 23:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_alter_employee_options_employee_city_and_more"),
        ("payrolls", "0006_alter_payroll_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payroll",
            options={
                "ordering": ["-month", "-created_at"],
                "verbose_name": "Payroll",
                "verbose_name_plural": "Payrolls",
            },
        ),
        migrations.AlterUniqueTogether(
            name="payroll",
            unique_together={("employee", "month")},
        ),
        migrations.AddField(
            model_name="payroll",
            name="gross_salary",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Gross salary amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="insurance_deduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Insurance deduction (BPJS, etc.)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="net_pay",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Net pay after deductions",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="notes",
            field=models.TextField(blank=True, help_text="Additional notes"),
        ),
        migrations.AddField(
            model_name="payroll",
            name="other_deduction",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Other deductions", max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="payment_date",
            field=models.DateField(
                blank=True, help_text="Date when payroll was paid", null=True
            ),
        ),
        migrations.AddField(
            model_name="payroll",
            name="tax_deduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Income tax deduction",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payrolls",
                to="employees.employee",
                verbose_name="Employee",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="month",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Payroll period (month/year)",
            ),
        ),
        migrations.AlterField(
            model_name="payroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=100,
            ),
        ),
        migrations.RemoveField(
            model_name="payroll",
            name="amount",
        ),
    ]
