# Generated by Django 5.1.7 on 2025-12-06 14:56

import core.utils
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillOfMaterials",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(blank=True, max_length=100)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        help_text="Quantity of product produced by this BOM",
                        max_digits=12,
                    ),
                ),
                (
                    "bom_type",
                    models.CharField(
                        choices=[
                            ("normal", "Manufacture this product"),
                            ("kit", "Kit / Package"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "ready_time",
                    models.PositiveIntegerField(
                        default=0, help_text="Production time in minutes"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product to be manufactured",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="boms",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bill of Materials",
                "verbose_name_plural": "Bills of Materials",
                "ordering": ["product__name"],
            },
        ),
        migrations.CreateModel(
            name="BOMLine",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Quantity of component needed",
                        max_digits=12,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Component/ingredient product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bom_lines",
                        to="products.product",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave empty to use product default UoM",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.unitofmeasure",
                    ),
                ),
            ],
            options={
                "ordering": ["bom", "id"],
            },
        ),
        migrations.CreateModel(
            name="ManufacturingOrder",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reference", models.CharField(blank=True, max_length=50, unique=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, help_text="Quantity to produce", max_digits=12
                    ),
                ),
                (
                    "quantity_produced",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Quantity actually produced",
                        max_digits=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("confirmed", "Confirmed"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateTimeField(blank=True, null=True)),
                ("date_started", models.DateTimeField(blank=True, null=True)),
                ("date_finished", models.DateTimeField(blank=True, null=True)),
                ("origin", models.CharField(blank=True, max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("0", "Not Urgent"),
                            ("1", "Normal"),
                            ("2", "Urgent"),
                            ("3", "Very Urgent"),
                        ],
                        default="1",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manufacturing_orders",
                        to="manufacturing.billofmaterials",
                    ),
                ),
                (
                    "destination_location",
                    models.ForeignKey(
                        help_text="Location to store finished product",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mo_destination",
                        to="inventory.location",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manufacturing_orders",
                        to="products.product",
                    ),
                ),
                (
                    "source_location",
                    models.ForeignKey(
                        help_text="Location to consume components from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mo_source",
                        to="inventory.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manufacturing Order",
                "verbose_name_plural": "Manufacturing Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ManufacturingOrderLine",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_required",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Required quantity based on BOM",
                        max_digits=12,
                    ),
                ),
                (
                    "quantity_consumed",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.00"),
                        help_text="Actually consumed quantity",
                        max_digits=12,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manufacturing_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="manufacturing.manufacturingorder",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mo_lines",
                        to="products.product",
                    ),
                ),
                (
                    "uom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="products.unitofmeasure",
                    ),
                ),
            ],
            options={
                "ordering": ["manufacturing_order", "id"],
            },
        ),
    ]
