# Generated by Django 5.1.7 on 2025-12-13 23:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0003_employeesetting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Employee",
                "verbose_name_plural": "Employees",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="country",
            field=models.CharField(default="Indonesia", max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(
                choices=[
                    ("hr", "Human Resources"),
                    ("finance", "Finance & Accounting"),
                    ("it", "Information Technology"),
                    ("sales", "Sales & Marketing"),
                    ("operations", "Operations"),
                    ("manufacturing", "Manufacturing"),
                    ("purchasing", "Purchasing"),
                    ("warehouse", "Warehouse"),
                    ("general", "General"),
                ],
                default="general",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="employee",
            name="employee_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated employee ID",
                max_length=50,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[
                    ("full_time", "Full Time"),
                    ("part_time", "Part Time"),
                    ("contract", "Contract"),
                    ("intern", "Intern"),
                ],
                default="full_time",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the employee"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="employee",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="employee",
            name="street",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="employee",
            name="actor",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employee_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="salary",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Monthly salary", max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
